matrix:
  include:
    - rvm: 2.6
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.6
    - rvm: 2.5
    - rvm: 2.4
    - rvm: 2.3
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-19mode
