name: Ruby

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: 2.6.x
          - ruby-version: 2.4.x
            bundler-version: 1.17.3
            gemfile: gemfiles/rails_4.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Bundler
        if: ${{ matrix.bundler-version }}
        run: |
          gem uninstall bundler
          gem install bundler -v ${{ matrix.bundler-version }}
      - name: Build and test
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake
